### ISSUE TITLE
Proper package

### ISSUE THREAD

**Issue by phase** [QuantumTheoryMC/QuantumAPI#2]
You should put your files into `org.quantumapi` instead of `quanta`.

**Comment by Caritas-Dei** [comment]
I will do that when the index.html in the home page doesn't have just a header and a footer. I'll keep this open to remind myself. Currently, I'm building a simple website template with an object-oriented design.

I digress. If you have any knowledge of it, do you think I should use Sass?

**Comment by phase** [comment]
It doesn't have to do so much with the website itself, just the domain. You put the domain of your project as the package.

And I just do CSS.

**Comment by Caritas-Dei** [comment]
Very well. I'll update the package for the next release.

Thanks

**Comment by Caritas-Dei** [comment]
It would seem I can't find a suitable tag for this...

**Comment by phase** [comment]
`bug` is for stuff that doesn't work
`enhancement` is for stuff to be added/changed
I'd go with `enhancement`.
