### ISSUE TITLE
LaunchWrapper

### ISSUE THREAD

**Issue by PizzaCrust** [QuantumTheoryMC/QuantumAPI#7]
LaunchWrapper is a better solution that using agents, it allows you to prevent circular exceptions

**Comment by Caritas-Dei** [comment]
I'm trying to keep this as lightweight as possible. LaunchWrapper is for class modifications; what we want is to load mods, which is done simply by appending the mod jar file to the system ClassLoader search through JMX Instrumentation as a Java Agent. This also allows loading the API simply as a JVM argument.

Also, what do you mean by circular exceptions?

**Comment by PizzaCrust** [comment]
The default class loader doesn't really help you with 'circular' issues.

Example:

TestTransformer -> Target -> TestTransformer -> Target -> **to infinity**

**Comment by Caritas-Dei** [comment]
Quantum API probably won't need to handle class transformations until I make Extensions, and I probably will not be using any sort of Mixins or Agents to do that whatsoever.

I will be allowing a new idea called Quantum Modules, which essentially I got the idea from how the Linux kernel works: Quantum API  will eventually be split into tiny modules that are loaded in any arbitrary sequence. These modules can even modify code and change the behavior of Quantum API. To an extent: 3rd party modules cannot break any basic functionality of the API or wrapper that would cause incompatibilities between versions. A module may modify the minecraft base, just like core mods, to allow modification of _functionality_.

You see, the API will allow modification of game behavior, not functionality (what something does, not how something works). Mods will allow changes to behavior (the what), while modules can change functionality (the how).
