### ISSUE TITLE
Switch to ASM

### ISSUE THREAD

**Issue by PizzaCrust** [QuantumTheoryMC/QuantumAPI#8]
More viable and long term solution allowing to do more.

**Comment by Caritas-Dei** [comment]
Switching to ASM will only give me headaches. Javassist is easier to use and lightweight.

**Comment by PizzaCrust** [comment]
How about proposing a new bytecode API that will implement ASM. I will volunteer to work on it.

**Comment by Caritas-Dei** [comment]
Better idea: we'll use javassist for now. When production comes around, we'll make our own bytecode framework.

**Comment by Caritas-Dei** [comment]
Closing this for now.
