### ISSUE TITLE
Blocks class should be a regular class

### ISSUE THREAD

**Issue by PizzaCrust** [QuantumTheoryMC/QuantumAPI#9]
The class can't be extended to use modded blocks.

**Comment by Caritas-Dei** [comment]
Please clarify

**Comment by Caritas-Dei** [comment]
quantum.Blocks is intended to provide access to instances of blocks. The fields are mutable so that block overrides can be written to those fields.

**Comment by PizzaCrust** [comment]
quick response, that isn't what I meant. I meant that the class should be a regular class to allow to add more fields/possible hashmap that contains all blocks instead of the default blocks. hope to work on this!

**Comment by Caritas-Dei** [comment]
quantum.Quantum already has a list of all blocks. Blocks is only intended for Minecraft blocks. Mods rarely interact with hard references to other mods. If a mod wants a list of their added blocks, they'll have to make their own Blocks class that contains them.

**Comment by PizzaCrust** [comment]
Please refactor the class name into VanillaBlocks, newer APIs are defining mod blocks into the class called Blocks and may cause confusion.
